name: Loading Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Testing packages
        env:
          repo: ${{ github.repository }}
        run: |
          pip install https://github.com/mpkg-project/mpkg/archive/master.zip -q
          mpkg set debug yes
          mpkg set unsafe yes
          mpkg load "https://github.com/zpcc/mpkg-pkgs/raw/master/parser/common.py->common-zpcc.py" --config
          git diff HEAD^ HEAD --diff-filter=ACMR --name-only|awk '/packages\/.*[\.py|\.json]$/{print}'|xargs -I {} mpkg load "https://github.com/$repo/raw/master/{}"
